BBBBBBB BBBBBBBBBBB
BBBB BBBB

BBBBB BBBBBBBBBBB
          XXXX XXXXXXXXXXXXX XXXXXXXXXXXXXXXX XXXXXXXXXXXX XXXXXXXXXX
                    XXX XXXXXXXXXXXXXXXXX XXXXXXXXX
                        XXX XXXXXXXXXXXXXXX XXXXXXXX
                            XX XXXXXXXXXXXXXXXX XXXXXXXXXXX XXXXXXXXXX XXXXXXXXXXXXX  gettext(u'Tabrara') XXXX
                        XXXXX
                    XXXXX
                    XXX XXXXXXXXXXXXXXXXXXX
                        XXX XXXXXXXXXXXXXXXXX
                            XX XXXXXXXXXXXXXXXX XXXXXXBBB BBBBBBBXXXX XXXXXXXXXX XXXXXXXXXXXXXXXXXXXX  gettext(u'Login') XXXX
                        XXXXX
                    XXXXX
          XXXXXX
BBBBBBBB

BBBBB BBBBBBB
XXXX XXXXXXXXXXXXXXXXXXXXXX
  XXX XXXXXXXXXXXXXXXXXX XXXXXXX XXXX XXXXXX gettext(u'Register') XXXXX
  XXXXX XXXXXXXXXXXXX XXXXXXXXXXX
    BBBBBBBBBB
    XXXX XXXXXXXXXXXXXXXXX XXXXXXXXXXXXXXXXXX
      
      XXXXXX XXXXXXX gettext(u'Phone number') XXXXXXXX
      XXXXXX XXXXXXXXXXXXXXXX XXXXXXXXXXXXXXXXXXXXX
      XXXXXXXXX XXXXXXXXXXXXXXXXX XXXXXXXXXXXXXXXX XXXXXXXXXXXXXXXXXXXXXX
        XXXXXXXX
                                      XXX XXXXXX X XX XXXXXXX XXXXXXXXXXXXXXXX
                                      XXXXXXXXXXXXXXXXXXXXXXXXXXXXX
                                                XXXXX XXXXXXX
                                                XXXXXXX XXXXXX
                                                XXXXXXXXXXXX X XXXX X XXXXXXXXXX XXXXXXXX XXXXXXXXXXXX XXXX
                                                XXXXXXXXXXXX XX
                                      XXX
        XXXXXXXXX
    XXXXXX
    XXXXXXX XXXXXXXXXXXXXXXXXXXXXXX
      XXX XXXXXXX X XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX
      XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX
    XXXXXXXXX
    XXXXXXX XXXXXXXXXXXXXXXXX XXXXXXXXXXXXXXXXXX
      
      XXXXXX XXXXXXX gettext(u'Email') XXXXXXXX
      
      XXXXXX XXXXXXXXXXXXXX XXXXXXXXXXXXXXXX XXXXXXXXXXXXXXXXXXXX
    XXXXXX
    XXXXXXX XXXXXXXXXXXXXXXXXXXXXXX
      XXX XXXXXXX X XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX
      XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX
    XXXXXXXXXXX
    XXXX XXXXXXXXXXXXXXXXX XXXXXXXXXXXXXXXXXX
      
      XXXXXX XXXXXXX gettext(u'Password') XXXXXXXX
      
      XXXXXX XXXXXXXXXXXXXXXXXX XXXXXXXXXXXXXXXX XXXXXXXXXXXXFFFFXXXXXXXX
    XXXXXX
    XXXXXXX XXXXXXXXXXXXXXXXXXXXXXX
      XXX XXXXXXX X XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX
      XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX
    XXXXXXXXX
    XXXX XXXXXXXXXXXXXXXXX XXXXXXXXXXXXXXXXXX
      
      XXXXXX XXXXXXX gettext(u'Password confirmation') XXXXXXXX
      XXXXXX XXXXXXXXXXXXXXXX XXXXXXXXXXXXXXXXXXXXX
    XXXXXX
    XXXXXXX XXXXXXXXXXXXXXXXXXXXXXX
      XXX XXXXXXX X XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX
      XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX
    XXXXXXXXX
    XXXX XXXXXXXXXXXXXXXXXXX
        XXXXXXX XXXXXXXXXXXXX XXXXXXXXXX XXXXXXXXXXX XXXXXXXXX XXXXXXXXX XXXXXXXX gettext(u'Submit') XXXXXXXXX
    XXXXXX
  XXXXXXX
XXXXXX
BBBBBBBB
