# Generated by Django 2.2.7 on 2020-07-30 15:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='active',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='product',
            name='image',
            field=models.ImageField(blank=True, upload_to='images/products'),
        ),
        migrations.AddField(
            model_name='product',
            name='unit_price',
            field=models.CharField(default='Unit price', help_text='Product unit price', max_length=20),
        ),
    ]
