# Generated by Django 2.2.16 on 2020-10-19 17:15

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import products.models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('products', '0004_auto_20200924_1050'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='showcaseinfo',
            name='owner',
        ),
        migrations.AddField(
            model_name='showcaseinfo',
            name='active',
            field=models.BooleanField(default=True),
        ),
        migrations.AlterField(
            model_name='product',
            name='name',
            field=models.CharField(help_text='Product name', max_length=100),
        ),
        migrations.AlterField(
            model_name='product',
            name='unit_price',
            field=models.CharField(help_text='Product unit price', max_length=20),
        ),
        migrations.AlterField(
            model_name='showcaseinfo',
            name='description',
            field=models.TextField(blank=True, help_text='Info block description', max_length=4000, null=True),
        ),
        migrations.AlterField(
            model_name='showcaseinfo',
            name='title',
            field=models.CharField(help_text='Info block title', max_length=100),
        ),
        migrations.CreateModel(
            name='Showcase',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, primary_key=True, serialize=False, unique=True)),
                ('title', models.CharField(help_text='Showcase title', max_length=100)),
                ('image', models.ImageField(blank=True, upload_to=products.models.upload_showcase_image_to)),
                ('owner', models.ForeignKey(help_text='Owner', null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.AddField(
            model_name='showcaseinfo',
            name='showcase',
            field=models.ForeignKey(help_text='Showcase', null=True, on_delete=django.db.models.deletion.SET_NULL, to='products.Showcase'),
        ),
    ]
