XXXX XXXXXXXXXXXX XXXXXXXXXXX XXXXXXXX
  XX XXXXXXXXXXXX XXXXXXXXXXX XXXXXXBBB BBBBBBBBBBBBBBBBBBBBBBBBBBBB BBBBBBBBBBBXX
    XX XXXXXXXXXXXXXXXXXXXXXXX
  XXXX
  
  XXXX
    XX XXXXXXXXXXXXXXXXBB BBBBBBBBBBBBBXXXXBBBBBXXXXXX
     
    
    BB BBBBBBBBBBBBB
      XX 
    BBBBB
  XXXXX
  
  XXX XXXXXXX
  
  XXXFFFFFFFFFFFFXXXX
  
  XXXX XXXXXXXXXXXXXXXXXXXXXXX
    BBB BBBBBB BB BBBBBBBBBBBBBBBBBBB
      XX XXXXXXXXXXX XXXXXXXXXXXX
    BBBBBB
  XXXXXX
XXXXXX