BBBBBBB BBBBBBBBBBB
BBBB BBBB

BBBBB BBBB
    BBBB BBBBBBBBBBB
BBBBBBBB

BBBBB BBBBBBBBBBB
          XXXX XXXXXXXXXXXXX XXXXXXXXXXXXXXXX XXXXXXXXXXXX XXXXXXXXXX
                    XXX XXXXXXXXXXXXXXXXX XXXXXXXXX
                        XXX XXXXXXXXXXXXXXX XXXXXXXX
                            XX XXXXXXXXXXXXXXXX XXXXXXXXXXX XXXXXXXXXX XXXXXXXXXXXXX  gettext(u'Tabrara') XXXX
                        XXXXX
                    XXXXX
          XXXXXX
BBBBBBBB

BBBBB BBBBBBB
XXXX XXXXXXXXXXXXXXXXXXXXXX
    XXX XXXXXXXXXXXXXXXXXX XXXXXXX XXXX XXXXXX gettext(u'Login') XXXXX
    XXXXX XXXXXXXXXXXXX XXXXXXXXXX  XXXXXXXXXXXXXXXXXXXXXXX XXXXXXXXXX XXXXXXXXXXX
      BBBBBBBBBB
      XXXX XXXXXXXXXXXXXXXXX XXXXXXXXXXXXXXXXXX
        
        
        XXXXXX XXXXXXX gettext(u'Phone number') XXXXXXXX
        XXXX XXXXXXXXXXXXXXXXXXXXXXXXX
             gettext(u'Contact phone number required, format: +7(123) 456-78-90') 
        XXXXXX
        XXXXXXXX
                                      XXX XXXXXX X XX XXXXXXX XXXXXXXXXXXXXXXX
                                      XXXXXXXXXXXXXXXXXXXXXXXXXXXXX
                                                XXXXX XXXXXXX
                                                XXXXXXX XXXXXX
                                                XXXXXXXXXXXX X XXXX X XXXXXXXXXX XXXXXXXX XXXXXXXXXXXX XXXX
                                                XXXXXXXXXXXX XX
                                      XXX
        XXXXXXXXX
      XXXXXX
      XXXXXXX XXXXXXXXXXXXXXXXXXXXXXX
        XXX XXXXXXX X XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX
        XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX
      XXXXXXXXX
      XXXX XXXXXXXXXXXXXXXXX XXXXXXXXXXXXXXXXXX
        
        
        XXXXXX XXXXXXX gettext(u'Password') XXXXXXXX
      XXXXXX
      XXXXXXX XXXXXXXXXXXXXXXXXXXXXXX
        XXX XXXXXXX X XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX
        XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX
      XXXXXXXXX

      XXXX XXXXXXXXXXXXXXXXXXX
        XXXXXXX XXXXXXXXXXXXX XXXXXXXXXX XXXXXXXXXXX XXXXXXXXX XXXXXXXXX XXXXXXXX gettext(u'Sign in') XXXXXXXXX
      XXXXXX

     XXXXXXX
    XXX gettext(u'Forgot password') X XX XXXXXXBBB BBBBBBBBBBBBBBBBXX gettext(u'Reset it') XXXXXXXXX
    XXX gettext(u'Not member') X XX XXXXXXBBB BBBBBBBBBBBBBBBBBBBBBBBBBBBBBBXX gettext(u'Register') XXXXXXXXX
    XXX XXXXXXXXXXXXX

    XX XXXXXXBBB BBBBBBBBBBBBBB BBBBBBBBBBBBBBBX XXXXXXXXXX XXXXXXXXXX XXXXXXXXX XXXXXXXXX XXXXXXXX
          XX XXXXXXXXXX XXXXXXXXXXXXXXX
          XXXX XXXX XX XXXX XXXXXXXXXXXXX
    XXXX

XXXXXX

BBBBBBBB
